/***********************************************************************************************************************************
* Class Name   : CONSTANTS
* Description  : This class for declare the constants to the registration
* Author       : Pankaj
* Created On   : 07/09/2020
* Modification Log:  
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer             Date             Description 
* ---------------------------------------------------------------------------------------------------------------------------------------
* Pankaj             07/09/2020       Initial Implementation
**************************************************************************************************************************************/

public class CONSTANTS {
    public static final String USER_REGISTRATION_STATUS_APP_APPROVED = 'App Approved';
    public static final String USER_REGISTRATION_STATUS_APP_REJECTED = 'App Rejected';
    public static final String USER_REGISTRATION_STATUS_APP_REQUESTED = 'App Requested';
    public static final String USER_REGISTRATION_STATUS_VERIFIED = 'Verified';

}