public with sharing class MARS_Constants {

    public static final String APP_REQUESTED = 'App Requested';
    public static final String AGENCY_CHANGE_REQUESTED = 'Agency Change Requested';
    public static final String NEW_AGENCY_REQUESTED = 'Agency Access Requested';
    /*public static final string APP_REQUESTED = 'App Requested';
    public static final string APP_REQUESTED = 'App Requested';
    public static final string APP_REQUESTED = 'App Requested';*/

    public static final String PERSONNEL_BASE_RATE='Personnel Base Rate';
    public static final String LINE_ITEM_TYPE_PERSONNEL = 'Personnel';
    public static final String SURVEY_STATUS_APPROVED = 'Approved';
    public static final String SURVEY_STATUS_REVISED = 'Revised';
    public static final String SURVEY_STATUS_ACTIVE = 'Active';
    public static final String SURVEY_STATUS_PENDING_APPROVAL = 'Pending for Approval';
    public static final String SURVEY_STATUS_EXPIRED = 'Expired';
    public static final String SURVEY_STATUS_PENDING_REVIEW = 'Pending Review';
    public static final String SURVEY_STATUS_REVIEWED = 'Reviewed';
}