/**
 * Created by Pankaj on 10-04-2020.
 */

@IsTest
private class UserTriggerHelperTest {
    /*@IsTest
    static void testBehavior() {

        Test.startTest();

        Id p = [select id from profile where name='PHOS Customer Community Plus Login User'].id;

        Account ac = new Account(name ='01 - Alameda') ;
        insert ac;

        Contact con = new Contact(LastName ='testCon',AccountId = ac.Id);
        insert con;

        User user = new User(alias = 'test123', email='test123@noemail.com',
                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                localesidkey='en_US', profileid = p, country='United States',IsActive =true,
                ContactId = con.Id, County__c = '01 - Alameda',
                timezonesidkey='America/Los_Angeles', username='tester@noemail.com');

        insert user;

        Test.stopTest();
    }*/
}